### PR TITLE
Some tweaks

### PR DESCRIPTION
**Pull request by Pernat1y**
Added openSUSE (testing/WIP. Not in the list of supported OSes)
Updated url for Arch Linux
'curl' replaced with 'wget' (it should be more reliable)
More DNS servers (added Cloudflare and secondary Google servers)
Minor refactoring and code alignment

### CODE REVIEW

**Comment by YadominJinta** [comment]
1. I don't like wget.
2. I don't think arch url need to update.
3. opensuse image is too big to use .

**Comment by Pernat1y** [comment]
1. Ok, will revert this change
2. New url points to balancer, not one server
3. 230  MB is not that large. Especially for recent tablets/smartphones

**Comment by YadominJinta** [comment]
Maybe opensuse docker image will be better. But I can't use `zypper update` in China .Maybe due to the firewall in China.

**Comment by YadominJinta** [comment]
I won't release a new version before I graduate from senior high school next year. So you pull request won't release before 2019.6.8 .

**Comment by YadominJinta** [comment]
Thank you very much.

**Comment by YadominJinta** [comment]
Docker image
https://github.com/openSUSE/docker-containers-build/tree/openSUSE-Tumbleweed

**Pull request merged**
